" Normal setting
set number relativenumber  " turn hybrid line number on
set showcmd "show command in bottom bar
set cursorline  "highlight current line
set wildmenu   "visual autocomplete for command menu
set lazyredraw  "redraw only when we need to
set showmatch  "highlight matching [{()}]

"New movement keymap
inoremap hh <ESC>
noremap ; l
noremap l k
noremap k j
noremap j h

" Theme
syntax enable
set background=dark
colorscheme gruvbox

set tabstop=4   " number of visual spaces per TAB
set softtabstop=4  "number of spaces in tab when editing
set expandtab   "tabs are spaces
set incsearch  "search as characters are enterd
set hlsearch  "highlight matches

" Search down into subdirectories
" Provides tab-completion for all file-related tasks
set path+=**

set clipboard=unnamedplus  " Copy to clipboard "+y

" netrw magic
let g:netrw_banner = 0 "hide netrw top banner
let g:netrw_list_hide = '.*\.swap$'  " Hide vim.swp files
let g:netrw_liststyle = 3  " Change the directory view in netrw
let g:netrw_browse_split = 4 " Open on previous vim
let g:netrw_altv = 1
let g:netrw_winsize = 25 " size of left window
" Open Vexplor automatically
augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * :Vexplore
augroup END

" Toggle Vexplore with Ctrl-E
"function! ToggleVExplorer()
"  if exists("t:expl_buf_num")
"      let expl_win_num = bufwinnr(t:expl_buf_num)
"      if expl_win_num != -1
"          let cur_win_nr = winnr()
"          exec expl_win_num . 'wincmd w'
"          close
"          exec cur_win_nr . 'wincmd w'
"          unlet t:expl_buf_num
"      else
"          unlet t:expl_buf_num
"      endif
"  else
"      exec '1wincmd w'
"      Vexplore
"      let t:expl_buf_num = bufnr("%")
"  endif
"endfunction
"map <silent> <C-E> :call ToggleVExplorer()<CR>

" Per default, netrw leaves unmodified buffers open. This autocommand
" deletes netrw's buffer once it's hidden (using ':q', for example)
autocmd FileType netrw setl bufhidden=delete
